export const videos = [
  {
    id: "1",
    uri: require("@/assets/videos/video1.mp4"),
    author: "Author1",
    description: "This is a sample description for video 1",
    hashtags: "#fun #reactnative",
    datePosted: "2 hours ago",
    likes: 120,
    comments: 45,
    bookmarks: 30,
  },
  {
    id: "2",
    uri: require("@/assets/videos/video2.mp4"),
    author: "Author2",
    description: "This is a sample description for video 2",
    hashtags: "#cool #videolar",
    datePosted: "3 hours ago",
    likes: 150,
    comments: 60,
    bookmarks: 40,
  },
  {
    id: "3",
    uri: require("@/assets/videos/video3.mp4"),
    author: "Author4",
    description: "This is a sample description for video 3",
    hashtags: "#cool #videolar",
    datePosted: "3 hours ago",
    likes: 150,
    comments: 60,
    bookmarks: 40,
  },
  {
    id: "4",
    uri: require("@/assets/videos/video4.mp4"),
    author: "Author4",
    description: "This is a sample description for video 4",
    hashtags: "#cool #videolar",
    datePosted: "3 hours ago",
    likes: 150,
    comments: 60,
    bookmarks: 40,
  },
];
